const Attributes = `
| Name                  | Description                                                                                                                                                            | Type                                                                                                                                                                                                                                                           | Default                                                                                |
| --------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------- |
| locale                | Locale Object                                                                                                                                                          | ^[object]\`{name: string, el: TranslatePair}\`[](https://github.com/element-plus/element-plus/blob/a98ff9b40c0c3d2b9959f99919bd8363e3e3c25a/packages/locale/index.ts#L5) [languages](https://github.com/element-plus/element-plus/tree/dev/packages/locale/lang) | [en](https://github.com/element-plus/element-plus/blob/dev/packages/locale/lang/en.ts) |
| size                  | global component size                                                                                                                                                  | ^[enum]\`'large' | 'default' | 'small'\`                                                                                                                                                                                                                       | default                                                                                |
| zIndex                | global Initial zIndex                                                                                                                                                  | ^[number]                                                                                                                                                                                                                                                      | —                                                                                      |
| namespace             | global component className prefix (cooperated with [$namespace](https://github.com/element-plus/element-plus/blob/dev/packages/theme-chalk/src/mixins/config.scss#L1)) | ^[string]                                                                                                                                                                                                                                                      | el                                                                                     |
| button                | button related configuration, [see the following table](#button-attributes)                                                                                            | ^[object]\`{autoInsertSpace?: boolean}\`                                                                                                                                                                                                                         | see the following table                                                                |
| message               | message related configuration, [see the following table](#message-attributes)                                                                                          | ^[object]\`{max?: number}\`                                                                                                                                                                                                                                      | see the following table                                                                |
| experimental-features | features at experimental stage to be added, all features are default to be set to false                                                                                | ^[object]                                                                                                                                                                                                                                                      | —                                                                                      |
`;
const Slots = `
| Name    | Description               | Scope                                                   |
| ------- | ------------------------- | ------------------------------------------------------- |
| default | customize default content | config: provided global config (inherited from the top) |
`;

export default {
  attributes: Attributes,
  slots: Slots,
};
