const Attributes = `
| Name                  | Description                                                                                                                                                                                                                    | Type                                                                      | Default                                                            |
| --------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| model-value / v-model | binding value                                                                                                                                                                                                                  | ^[number]                                                                 | 0                                                                  |
| max                   | max rating score                                                                                                                                                                                                               | ^[number]                                                                 | 5                                                                  |
| size                  | size of Rate                                                                                                                                                                                                                   | ^[enum]\`'large' | 'default' | 'small'\`                                  | —                                                                  |
| disabled              | whether Rate is read-only                                                                                                                                                                                                      | ^[boolean]                                                                | false                                                              |
| allow-half            | whether picking half start is allowed                                                                                                                                                                                          | ^[boolean]                                                                | false                                                              |
| low-threshold         | threshold value between low and medium level. The value itself will be included in low level                                                                                                                                   | ^[number]                                                                 | 2                                                                  |
| high-threshold        | threshold value between medium and high level. The value itself will be included in high level                                                                                                                                 | ^[number]                                                                 | 4                                                                  |
| colors                | colors for icons. If array, it should have 3 elements, each of which corresponds with a score level, else if object, the key should be threshold value between two levels, and the value should be corresponding color         | ^[object]\`string[] | Record<number, string>\`                             | ['#F7BA2A', '#F7BA2A', '#F7BA2A']                                  |
| void-color            | color of unselected icons                                                                                                                                                                                                      | ^[string]                                                                 | #C6D1DE                                                            |
| disabled-void-color   | color of unselected read-only icons                                                                                                                                                                                            | ^[string]                                                                 | #EFF2F7                                                            |
| icons                 | icon components. If array, it should have 3 elements, each of which corresponds with a score level, else if object, the key should be threshold value between two levels, and the value should be corresponding icon component | ^[object]\`string[] | Component[] | Record<number, string | Component>\` | [StarFilled, StarFilled, StarFilled]                               |
| void-icon             | component of unselected icons                                                                                                                                                                                                  | ^[string] / ^[Component]                                                  | Star                                                               |
| disabled-void-icon    | component of unselected read-only icons                                                                                                                                                                                        | ^[string] / ^[Component]                                                  | StarFilled                                                         |
| show-text             | whether to display texts                                                                                                                                                                                                       | ^[boolean]                                                                | false                                                              |
| show-score            | whether to display current score. show-score and show-text cannot be true at the same time                                                                                                                                     | ^[boolean]                                                                | false                                                              |
| text-color            | color of texts                                                                                                                                                                                                                 | ^[string]                                                                 | #1F2D3D                                                            |
| texts                 | text array                                                                                                                                                                                                                     | ^[array]\`string[]\`                                                        | ['Extremely bad', 'Disappointed', 'Fair', 'Satisfied', 'Surprise'] |
| score-template        | score template                                                                                                                                                                                                                 | ^[string]                                                                 | {value}                                                            |
| clearable             | whether value can be reset to \`0\`                                                                                                                                                                                              | ^[boolean]                                                                | false                                                              |
| id                    | native \`id\` attribute                                                                                                                                                                                                          | ^[string]                                                                 | —                                                                  |
| label<A11yTag />      | same as \`aria-label\` in Rate                                                                                                                                                                                                   | ^[string]                                                                 | —                                                                  |
`;
const Events = `
| Name   | Description                         | Type                                 |
| ------ | ----------------------------------- | ------------------------------------ |
| change | Triggers when rate value is changed | ^[Function]\`(value: number) => void\` |
`;
const Exposes = `
| Name              | Description         | Type                                 |
| ----------------- | ------------------- | ------------------------------------ |
| setCurrentValue   | set current value   | ^[Function]\`(value: number) => void\` |
| resetCurrentValue | reset current value | ^[Function]\`() => void\`              |
`;
export default {
  attributes: Attributes,
  events: Events,
  exposes: Exposes,
};
