const Attributes = `
| Name                                           | Description                                                                                                                                                                                                                                                                 | Type                                                                                                                                                                 | Accepted Values                             | Default                                                                                                                 |
| ---------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------- |
| data                                           | Table data                                                                                                                                                                                                                                                                  | array                                                                                                                                                                | —                                           | —                                                                                                                       |
| height                                         | Table's height. By default it has an \`auto\` height. If its value is a number, the height is measured in pixels; if its value is a string, the value will be assigned to element's style.height, the height is affected by external styles                                   | string / number                                                                                                                                                      | —                                           | —                                                                                                                       |
| max-height                                     | Table's max-height. The legal value is a number or the height in px.                                                                                                                                                                                                        | string / number                                                                                                                                                      | —                                           | —                                                                                                                       |
| stripe                                         | whether Table is striped                                                                                                                                                                                                                                                    | boolean                                                                                                                                                              | —                                           | false                                                                                                                   |
| border                                         | whether Table has vertical border                                                                                                                                                                                                                                           | boolean                                                                                                                                                              | —                                           | false                                                                                                                   |
| size                                           | size of Table                                                                                                                                                                                                                                                               | string                                                                                                                                                               | large / default /small                      | —                                                                                                                       |
| fit                                            | whether width of column automatically fits its container                                                                                                                                                                                                                    | boolean                                                                                                                                                              | —                                           | true                                                                                                                    |
| show-header                                    | whether Table header is visible                                                                                                                                                                                                                                             | boolean                                                                                                                                                              | —                                           | true                                                                                                                    |
| highlight-current-row                          | whether current row is highlighted                                                                                                                                                                                                                                          | boolean                                                                                                                                                              | —                                           | false                                                                                                                   |
| current-row-key                                | key of current row, a set only prop                                                                                                                                                                                                                                         | string / number                                                                                                                                                      | —                                           | —                                                                                                                       |
| row-class-name                                 | function that returns custom class names for a row, or a string assigning class names for every row                                                                                                                                                                         | function({ row, rowIndex }) / string                                                                                                                               | —                                           | —                                                                                                                       |
| row-style                                      | function that returns custom style for a row, or an object assigning custom style for every row                                                                                                                                                                             | function({ row, rowIndex }) / object                                                                                                                               | —                                           | —                                                                                                                       |
| cell-class-name                                | function that returns custom class names for a cell, or a string assigning class names for every cell                                                                                                                                                                       | function({ row, column, rowIndex, columnIndex }) / string                                                                                                          | —                                           | —                                                                                                                       |
| cell-style                                     | function that returns custom style for a cell, or an object assigning custom style for every cell                                                                                                                                                                           | function({ row, column, rowIndex, columnIndex }) / object                                                                                                          | —                                           | —                                                                                                                       |
| header-row-class-name                          | function that returns custom class names for a row in table header, or a string assigning class names for every row in table header                                                                                                                                         | function({ row, rowIndex }) / string                                                                                                                               | —                                           | —                                                                                                                       |
| header-row-style                               | function that returns custom style for a row in table header, or an object assigning custom style for every row in table header                                                                                                                                             | function({ row, rowIndex }) / object                                                                                                                               | —                                           | —                                                                                                                       |
| header-cell-class-name                         | function that returns custom class names for a cell in table header, or a string assigning class names for every cell in table header                                                                                                                                       | function({ row, column, rowIndex, columnIndex }) / string                                                                                                          | —                                           | —                                                                                                                       |
| header-cell-style                              | function that returns custom style for a cell in table header, or an object assigning custom style for every cell in table header                                                                                                                                           | function({ row, column, rowIndex, columnIndex }) / object                                                                                                          | —                                           | —                                                                                                                       |
| row-key                                        | key of row data, used for optimizing rendering. Required if \`reserve-selection\` is on or display tree data. When its type is String, multi-level access is supported, e.g. \`user.info.id\`, but \`user.info[0].id\` is not supported, in which case \`Function\` should be used. | function(row) / string                                                                                                                                               | —                                           | —                                                                                                                       |
| empty-text                                     | Displayed text when data is empty. You can customize this area with \`#empty\`                                                                                                                                                                                                | string                                                                                                                                                               | —                                           | No Data                                                                                                                 |
| default-expand-all                             | whether expand all rows by default, works when the table has a column type="expand" or contains tree structure data                                                                                                                                                         | boolean                                                                                                                                                              | —                                           | false                                                                                                                   |
| expand-row-keys                                | set expanded rows by this prop, prop's value is the keys of expand rows, you should set row-key before using this prop                                                                                                                                                      | array                                                                                                                                                                | —                                           | —                                                                                                                       |
| default-sort                                   | set the default sort column and order. property \`prop\` is used to set default sort column, property \`order\` is used to set default sort order                                                                                                                               | object                                                                                                                                                               | (order: 'ascending' | 'descending')        | if \`prop\` is set, and \`order\` is not set, then \`order\` is default to ascending                                          |
| tooltip-effect                                 | the \`effect\` of the overflow tooltip                                                                                                                                                                                                                                        | string                                                                                                                                                               | dark / light                                | dark                                                                                                                    |
| tooltip-options<VersionTag version="2.2.28" /> | the options for the overflow tooltip, [see the following tooltip component](tooltip.html#attributes)                                                                                                                                                                        | ^[object]\`Pick<ElTooltipProps, 'effect' | 'enterable' | 'hideAfter' | 'offset' | 'placement' | 'popperClass' | 'popperOptions' | 'showAfter' | 'showArrow'>\` | [refer to tooltip](tooltip.html#attributes) | ^[object]\`{ enterable: true, placement: 'top', showArrow: true, hideAfter: 200, popperOptions: { strategy: 'fixed' } }\` |
| show-summary                                   | whether to display a summary row                                                                                                                                                                                                                                            | boolean                                                                                                                                                              | —                                           | false                                                                                                                   |
| sum-text                                       | displayed text for the first column of summary row                                                                                                                                                                                                                          | string                                                                                                                                                               | —                                           | Sum                                                                                                                     |
| summary-method                                 | custom summary method                                                                                                                                                                                                                                                       | function({ columns, data })                                                                                                                                        | —                                           | —                                                                                                                       |
| span-method                                    | method that returns rowspan and colspan                                                                                                                                                                                                                                     | function({ row, column, rowIndex, columnIndex })                                                                                                                   | —                                           | —                                                                                                                       |
| select-on-indeterminate                        | controls the behavior of master checkbox in multi-select tables when only some rows are selected (but not all). If true, all rows will be selected, else deselected.                                                                                                        | boolean                                                                                                                                                              | —                                           | true                                                                                                                    |
| indent                                         | horizontal indentation of tree data                                                                                                                                                                                                                                         | number                                                                                                                                                               | —                                           | 16                                                                                                                      |
| lazy                                           | whether to lazy loading data                                                                                                                                                                                                                                                | boolean                                                                                                                                                              | —                                           | —                                                                                                                       |
| load                                           | method for loading child row data, only works when \`lazy\` is true                                                                                                                                                                                                           | function(row, treeNode, resolve)                                                                                                                                     | —                                           | —                                                                                                                       |
| tree-props                                     | configuration for rendering nested data                                                                                                                                                                                                                                     | object                                                                                                                                                               | —                                           | \`{ hasChildren: 'hasChildren', children: 'children' }\`                                                                  |
| table-layout                                   | Sets the algorithm used to lay out table cells, rows, and columns                                                                                                                                                                                                           | string                                                                                                                                                               | fixed / auto                                | fixed                                                                                                                   |
| scrollbar-always-on                            | always show scrollbar                                                                                                                                                                                                                                                       | boolean                                                                                                                                                              | —                                           | false                                                                                                                   |
| flexible<VersionTag version="2.2.1" />         | ensure main axis minimum-size doesn't follow the content                                                                                                                                                                                                                    | boolean                                                                                                                                                              | —                                           | false                                                                                                                   |
`;
const Events = `
| Name               | Description                                                                                                                                  | Parameters                        |
| ------------------ | -------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------- |
| select             | triggers when user clicks the checkbox in a row                                                                                              | selection, row                    |
| select-all         | triggers when user clicks the checkbox in table header                                                                                       | selection                         |
| selection-change   | triggers when selection changes                                                                                                              | selection                         |
| cell-mouse-enter   | triggers when hovering into a cell                                                                                                           | row, column, cell, event          |
| cell-mouse-leave   | triggers when hovering out of a cell                                                                                                         | row, column, cell, event          |
| cell-click         | triggers when clicking a cell                                                                                                                | row, column, cell, event          |
| cell-dblclick      | triggers when double clicking a cell                                                                                                         | row, column, cell, event          |
| cell-contextmenu   | triggers when user right clicks on a cell                                                                                                    | row, column, cell, event          |
| row-click          | triggers when clicking a row                                                                                                                 | row, column, event                |
| row-contextmenu    | triggers when user right clicks on a row                                                                                                     | row, column, event                |
| row-dblclick       | triggers when double clicking a row                                                                                                          | row, column, event                |
| header-click       | triggers when clicking a column header                                                                                                       | column, event                     |
| header-contextmenu | triggers when user right clicks on a column header                                                                                           | column, event                     |
| sort-change        | triggers when Table's sorting changes                                                                                                        | \`{ column, prop, order }\`         |
| filter-change      | column's key. If you need to use the filter-change event, this attribute is mandatory to identify which column is being filtered             | filters                           |
| current-change     | triggers when current row changes                                                                                                            | currentRow, oldCurrentRow         |
| header-dragend     | triggers after changing a column's width by dragging the column header's border                                                              | newWidth, oldWidth, column, event |
| expand-change      | triggers when user expands or collapses a row (for expandable table, second param is expandedRows; for tree Table, second param is expanded) | row, (expandedRows | expanded)   |
`;
const Exposes = `
| Name             | Description                                                                                                                                                       | Parameters                                            |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| clearSelection     | used in multiple selection Table, clear user selection                                                                                                            | —                                                     |
| getSelectionRows   | returns the currently selected rows                                                                                                                               |                                                       |
| toggleRowSelection | used in multiple selection Table, toggle if a certain row is selected. With the second parameter, you can directly set if this row is selected                    | row, selected                                         |
| toggleAllSelection | used in multiple selection Table, toggle select all and deselect all                                                                                              | —                                                     |
| toggleRowExpansion | used in expandable Table or tree Table, toggle if a certain row is expanded. With the second parameter, you can directly set if this row is expanded or collapsed | row, expanded                                         |
| setCurrentRow      | used in single selection Table, set a certain row selected. If called without any parameter, it will clear selection.                                             | row                                                   |
| clearSort          | clear sorting, restore data to the original order                                                                                                                 | —                                                     |
| clearFilter        | clear filters of the columns whose \`columnKey\` are passed in. If no params, clear all filters                                                                     | columnKeys                                            |
| doLayout           | refresh the layout of Table. When the visibility of Table changes, you may need to call this method to get a correct layout                                       | —                                                     |
| sort               | sort Table manually. Property \`prop\` is used to set sort column, property \`order\` is used to set sort order                                                       | prop: string, order: string                           |
| scrollTo           | scrolls to a particular set of coordinates                                                                                                                        | (options: ScrollToOptions | number, yCoord?: number) |
| setScrollTop       | set vertical scroll position                                                                                                                                      | top                                                   |
| setScrollLeft      | set horizontal scroll position                                                                                                                                    | left                                                  |
`;
const Slots = `
| Name   | Description                                                                                                                                                                                   | Subtags      |
| ------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------ |
| -      | customize default content                                                                                                                                                                     | Table-column |
| append | Contents to be inserted after the last row. You may need this slot if you want to implement infinite scroll for the table. This slot will be displayed above the summary row if there is one. | —            |
| empty  | you can customize content when data is empty.                                                                                                                                                 | —            |
`;
export default {
  attributes: Attributes,
  events: Events,
  exposes: Exposes,
  slots: Slots,
};
