const Attributes = `
| Name                  | Description                                                                                                                                                                                                         | Type                                                                    | Accepted Values                                                                                                                  | Default                           |
| --------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------- | --------------------------------- |
| type                  | type of the column. If set to \`selection\`, the column will display checkbox. If set to \`index\`, the column will display index of the row (staring from 1). If set to \`expand\`, the column will display expand icon. | string                                                                  | selection / index / expand                                                                                                       | —                                 |
| index                 | customize indices for each row, works on columns with \`type=index\`                                                                                                                                                  | number / function(index)                                                | —                                                                                                                                | —                                 |
| label                 | column label                                                                                                                                                                                                        | string                                                                  | —                                                                                                                                | —                                 |
| column-key            | column's key. If you need to use the filter-change event, you need this attribute to identify which column is being filtered                                                                                        | string                                                                  | —                                                                                                                                | —                                 |
| prop                  | field name. You can also use its alias: \`property\`                                                                                                                                                                  | string                                                                  | —                                                                                                                                | —                                 |
| width                 | column width                                                                                                                                                                                                        | string / number                                                         | —                                                                                                                                | —                                 |
| min-width             | column minimum width. Columns with \`width\` has a fixed width, while columns with \`min-width\` has a width that is distributed in proportion                                                                          | string / number                                                         | —                                                                                                                                | —                                 |
| fixed                 | whether column is fixed at left / right. Will be fixed at left if \`true\`                                                                                                                                            | string / boolean                                                        | true / 'left' / 'right'                                                                                                          | —                                 |
| render-header         | render function for table header of this column                                                                                                                                                                     | function({ column, $index })                                          | —                                                                                                                                | —                                 |
| sortable              | whether column can be sorted. Remote sorting can be done by setting this attribute to 'custom' and listening to the \`sort-change\` event of Table                                                                    | boolean / string                                                        | custom                                                                                                                           | false                             |
| sort-method           | sorting method, works when \`sortable\` is \`true\`. Should return a number, just like Array.sort                                                                                                                       | function(a, b)                                                          | —                                                                                                                                | —                                 |
| sort-by               | specify which property to sort by, works when \`sortable\` is \`true\` and \`sort-method\` is \`undefined\`. If set to an Array, the column will sequentially sort by the next property if the previous one is equal        | function(row, index) / string / array                                   | —                                                                                                                                | —                                 |
| sort-orders           | the order of the sorting strategies used when sorting the data, works when \`sortable\` is \`true\`. Accepts an array, as the user clicks on the header, the column is sorted in order of the elements in the array     | array                                                                   | (the elements in the array need to be one of the following: \`ascending\`, \`descending\` and \`null\` restores to the original order) | ['ascending', 'descending', null] |
| resizable             | whether column width can be resized, works when \`border\` of \`el-table\` is \`true\`                                                                                                                                    | boolean                                                                 | —                                                                                                                                | true                              |
| formatter             | function that formats cell content                                                                                                                                                                                  | function(row, column, cellValue, index)                                 | —                                                                                                                                | —                                 |
| show-overflow-tooltip | whether to hide extra content and show them in a tooltip when hovering on the cell                                                                                                                                  | boolean | [\`object\`](#table-attributes)<VersionTag version="2.2.28" /> | Refer to table [tooltip-options](#table-attributes)                                                                              | —                                 |
| align                 | alignment                                                                                                                                                                                                           | string                                                                  | left / center / right                                                                                                            | left                              |
| header-align          | alignment of the table header. If omitted, the value of the above \`align\` attribute will be applied                                                                                                                 | string                                                                  | left / center / right                                                                                                            | —                                 |
| class-name            | class name of cells in the column                                                                                                                                                                                   | string                                                                  | —                                                                                                                                | —                                 |
| label-class-name      | class name of the label of this column                                                                                                                                                                              | string                                                                  | —                                                                                                                                | —                                 |
| selectable            | function that determines if a certain row can be selected, works when \`type\` is 'selection'                                                                                                                         | function(row, index)                                                    | —                                                                                                                                | —                                 |
| reserve-selection     | whether to reserve selection after data refreshing, works when \`type\` is 'selection'. Note that \`row-key\` is required for this to work                                                                              | boolean                                                                 | —                                                                                                                                | false                             |
| filters               | an array of data filtering options. For each element in this array, \`text\` and \`value\` are required                                                                                                                 | \`Array<{text: string, value: string}>\`                                  | —                                                                                                                                | —                                 |
| filter-placement      | placement for the filter dropdown                                                                                                                                                                                   | string                                                                  | top / top-start / top-end / bottom / bottom-start / bottom-end / left / left-start / left-end / right / right-start / right-end  | —                                 |
| filter-multiple       | whether data filtering supports multiple options                                                                                                                                                                    | boolean                                                                 | —                                                                                                                                | true                              |
| filter-method         | data filtering method. If \`filter-multiple\` is on, this method will be called multiple times for each row, and a row will display if one of the calls returns \`true\`                                                | function(value, row, column)                                            | —                                                                                                                                | —                                 |
| filtered-value        | filter value for selected data, might be useful when table header is rendered with \`render-header\`                                                                                                                  | array                                                                   | —                                                                                                                                | —                                 |
`;
const Slots = `
| Name   | Description                                                                        |
| ------ | ---------------------------------------------------------------------------------- |
| —      | Custom content for table columns. The scope parameter is \`{ row, column, $index }\` |
| header | Custom content for table header. The scope parameter is \`{ column, $index }\`       |
`;

export default {
  attributes: Attributes,
  slots: Slots,
};
