import type { TagDoc } from '@/types/tag-doc';
const doc: TagDoc.TagDocInstance = {
  url: 'component/popover.html',
  attributes: [
    {
      name: 'trigger',
      description: { cn: '触发方式', en: 'how the popover is triggered' },
      type: 'enum',
      default: 'click',
      value: ['click', 'focus', 'hover', 'contextmenu'],
    },
    {
      name: 'title',
      description: { cn: '标题', en: 'popover title' },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'effect',
      description: {
        cn: 'Tooltip 主题，Element Plus 内置了 `dark` / `light` 两种主题',
        en: 'Tooltip theme, built-in theme: <code>dark</code> / <code>light</code>',
      },
      type: 'enum',
      default: "'light'",
      value: ['dark', 'light'],
    },
    {
      name: 'content',
      description: {
        cn: '显示的内容，也可以通过写入默认 `slot` 修改显示内容',
        en: 'popover content, can be replaced with a default <code>slot</code>',
      },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'width',
      description: { cn: 'popover width', en: 'popover width' },
      type: ['string', 'number'],
      default: 'Min width 150px',
      value: [],
    },
    {
      name: 'placement',
      description: { cn: '出现位置', en: 'popover placement' },
      type: 'enum',
      default: 'bottom',
      value: ['top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left', 'left-start', 'left-end', 'right', 'right-start', 'right-end'],
    },
    {
      name: 'disabled',
      description: { cn: 'Popover 是否可用', en: 'whether Popover is disabled' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'visible',
      description: { cn: 'Popover 是否显示,支持双向绑定(v-model:visible)', en: 'whether popover is visible,support(v-model:visible)' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'offset',
      description: { cn: '出现位置的偏移量', en: 'popover offset' },
      type: 'number',
      default: '0',
      value: [],
    },
    {
      name: 'transition',
      description: { cn: '定义渐变动画', en: 'popover transition animation' },
      type: 'string',
      default: 'el-fade-in-linear',
      value: [],
    },
    {
      name: 'show-arrow',
      description: {
        cn: '是否显示 Tooltip 箭头， 欲了解更多信息，请参考[ElPopper](https://github.com/element-plus/element-plus/tree/dev/packages/components/popper) ',
        en: 'whether a tooltip arrow is displayed or not. For more info, please refer to [ElPopper](https://github.com/element-plus/element-plus/tree/dev/packages/components/popper)',
      },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'popper-options',
      description: {
        cn: '自定义 popper 选项，更多请参考[popper.js](https://popper.js.org/docs/v2/)',
        en: 'Customized popper option，更多请参考[popper.js](https://popper.js.org/docs/v2/)',
      },
      type: 'object',
      default: "{modifiers: [{name: 'computeStyles',options: {gpuAcceleration: false}}]}",
      value: [],
    },
    {
      name: 'popper-class',
      description: { cn: '为 popper 添加类名', en: 'custom class name for popover' },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'popper-style',
      description: { cn: '为 popper 自定义样式', en: 'custom style for popover' },
      type: ['string', 'object'],
      default: '—',
      value: [],
    },
    {
      name: 'show-after',
      description: { cn: '在触发后多久显示内容，单位毫秒', en: 'delay of appearance, in millisecond' },
      type: 'number',
      default: '0',
      value: [],
    },
    {
      name: 'hide-after',
      description: { cn: '延迟关闭，单位毫秒', en: 'delay of disappear, in millisecond' },
      type: 'number',
      default: '200',
      value: [],
    },
    {
      name: 'auto-close',
      description: { cn: 'tooltip 出现后自动隐藏延时，单位毫秒', en: 'timeout in milliseconds to hide tooltip' },
      type: 'number',
      default: '0',
      value: [],
    },
    {
      name: 'tabindex',
      description: {
        cn: 'Popover 组件的[tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)',
        en: '[tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) of Popover',
      },
      type: 'number',
      default: '—',
      value: [],
    },
    {
      name: 'teleported',
      description: { cn: '是否将 popover 的下拉列表插入至 body 元素', en: 'whether popover dropdown is teleported to the body' },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'persistent',
      description: {
        cn: '当 popover 组件长时间不触发且 `persistent` 属性设置为 false 时, `popover` 将会被删除',
        en: 'when popover inactive and <code>persistent</code> is <code>false</code> , popover will be destroyed',
      },
      type: 'boolean',
      default: 'true',
      value: [],
    },
  ],
  events: [
    {
      name: 'show',
      description: { cn: '显示时触发', en: 'triggers when popover shows' },
      type: 'function',
      param: '',
    },
    {
      name: 'before-enter',
      description: { cn: '显示动画播放前触发', en: 'triggers when the entering transition before' },
      type: 'function',
      param: '',
    },
    {
      name: 'after-enter',
      description: { cn: '显示动画播放完毕后触发', en: 'triggers when the entering transition ends' },
      type: 'function',
      param: '',
    },
    {
      name: 'hide',
      description: { cn: '隐藏时触发', en: 'triggers when popover hides' },
      type: 'function',
      param: '',
    },
    {
      name: 'before-leave',
      description: { cn: '隐藏动画播放前触发', en: 'triggers when the leaving transition before' },
      type: 'function',
      param: '',
    },
    {
      name: 'after-leave',
      description: { cn: '隐藏动画播放完毕后触发', en: 'triggers when the leaving transition ends' },
      type: 'function',
      param: '',
    },
  ],
  slots: [
    {
      name: 'default',
      description: { cn: 'Popover 内嵌 HTML 文本', en: 'text content of popover' },
    },
    {
      name: 'reference',
      description: { cn: '触发 Popover 显示的 HTML 元素', en: 'HTML element that triggers popover' },
    },
  ],
};
export default doc;
