import type { TagDoc } from '@/types/tag-doc';
const doc: TagDoc.TagDocInstance = {
  url: 'component/select.html',
  attributes: [
    {
      name: 'v-model',
      description: { cn: '选中项绑定值', en: 'binding value' },
      type: ['array', 'string', 'number', 'boolean', 'object'],
      default: '—',
      value: [],
    },
    {
      name: 'multiple',
      description: { cn: '是否多选', en: 'whether multiple-select is activated' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'disabled',
      description: { cn: '是否禁用', en: 'whether Select is disabled' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'value-key',
      description: {
        cn: '作为 value 唯一标识的键名，绑定值为对象类型时必填',
        en: 'unique identity key name for value, required when value is an object',
      },
      type: 'string',
      default: 'value',
      value: [],
    },
    {
      name: 'size',
      description: { cn: '输入框尺寸', en: 'size of Input' },
      type: 'enum',
      default: 'default',
      value: ['large', 'default', 'small'],
    },
    {
      name: 'clearable',
      description: { cn: '是否可以清空选项', en: 'whether select can be cleared' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'collapse-tags',
      description: { cn: '多选时是否将选中值按文字的形式展示', en: 'whether to collapse tags to a text when multiple selecting' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'collapse-tags-tooltip',
      description: {
        cn: '当鼠标悬停于折叠标签的文本时，是否显示所有选中的标签。 要使用此属性， <code>collapse-tags</code> 属性必须设定为 true',
        en: 'whether show all selected tags when mouse hover text of collapse-tags. To use this, <code>collapse-tags</code> must be true',
      },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'multiple-limit',
      description: {
        cn: '<code>multiple</code> 属性设置为 <code>true</code> 时，代表多选场景下用户最多可以选择的项目数，为 0 则不限制',
        en: 'maximum number of options user can select when <code>multiple</code> is <code>true</code>. No limit when set to 0',
      },
      type: 'number',
      default: '0',
      value: [],
    },
    {
      name: 'name',
      description: { cn: 'Select 输入框的原生 name 属性', en: 'the name attribute of select input' },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'effect',
      description: {
        cn: 'Tooltip 主题，内置了 <code>dark</code> / <code>light</code> 两种',
        en: 'Tooltip theme, built-in theme: <code>dark</code> / <code>light</code>',
      },
      type: 'enum',
      default: 'light',
      value: ['dark', 'light'],
    },
    {
      name: 'autocomplete',
      description: { cn: 'Select 输入框的原生 autocomplete 属性', en: 'the autocomplete attribute of select input' },
      type: 'string',
      default: 'off',
      value: [],
    },
    {
      name: 'placeholder',
      description: { cn: '占位文字', en: 'placeholder' },
      type: 'string',
      default: 'Select',
      value: [],
    },
    {
      name: 'filterable',
      description: { cn: 'Select 组件是否可筛选', en: 'whether Select is filterable' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'allow-create',
      description: {
        cn: '是否允许用户创建新条目， 只有当 <code>filterable</code> 设置为 true 时才会生效。',
        en: 'whether creating new items is allowed. To use this, <code>filterable</code> must be true',
      },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'filter-method',
      description: { cn: '自定义筛选方法', en: 'custom filter method' },
      type: 'function',
      default: '—',
      value: [],
    },
    {
      name: 'remote',
      description: { cn: '其中的选项是否从服务器远程加载', en: 'whether options are loaded from server' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'remote-method',
      description: { cn: '自定义远程搜索方法', en: 'custom remote search method' },
      type: 'function',
      default: '—',
      value: [],
    },
    {
      name: 'remote-show-suffix',
      description: { cn: '远程搜索方法显示后缀图标', en: 'in remote search method show suffix icon' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'loading',
      description: { cn: '是否正在从远程获取数据', en: 'whether Select is loading data from server' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'loading-text',
      description: { cn: '从服务器加载内容时显示的文本', en: 'displayed text while loading data from server' },
      type: 'string',
      default: 'Loading',
      value: [],
    },
    {
      name: 'no-match-text',
      description: {
        cn: '搜索条件无匹配时显示的文字，也可以使用 <code>empty</code> 插槽设置',
        en: 'displayed text when no data matches the filtering query, you can also use slot <code>empty</code>',
      },
      type: 'string',
      default: '无匹配数据',
      value: [],
    },
    {
      name: 'no-data-text',
      description: {
        cn: '无选项时显示的文字，也可以使用 <code>empty</code> 插槽设置自定义内容',
        en: 'displayed text when there is no options, you can also use slot <code>empty</code>',
      },
      type: 'string',
      default: '无数据',
      value: [],
    },
    {
      name: 'popper-class',
      description: { cn: '选择器下拉菜单的自定义类名', en: "custom class name for Select's dropdown" },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'popper-options',
      description: {
        cn: '自定义 popper 选项，更多请参考 <a href="https://popper.js.org/docs/v2/">popper.js</a>',
        en: 'Customized popper option see more at <a href="https://popper.js.org/docs/v2/">popper.js</a>',
      },
      type: 'object',
      default: '—',
      value: [],
    },
    {
      name: 'reserve-keyword',
      description: {
        cn: '当 <code>multiple</code> 和 <code>filter</code> 被设置为 true 时，是否在选中一个选项后保留当前的搜索关键词',
        en: 'when <code>multiple</code> and <code>filter</code> is true, whether to reserve current keyword after selecting an option',
      },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'default-first-option',
      description: {
        cn: '是否在输入框按下回车时，选择第一个匹配项。 需配合 <code>filterable</code> 或 <code>remote</code> 使用',
        en: 'select first matching option on enter key. Use with <code>filterable</code> or <code>remote</code>',
      },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'teleported',
      description: { cn: '是否将下拉列表元素插入 append-to 指向的元素下', en: 'whether select dropdown is teleported to the body' },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'persistent',
      description: {
        cn: '当下拉选择器未被激活并且 <code>persistent</code> 设置为 <code>false</code> ，选择器会被删除。',
        en: 'when select dropdown is inactive and <code>persistent</code> is <code>false</code>, select dropdown will be destroyed',
      },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'automatic-dropdown',
      description: {
        cn: '对于不可过滤的 Select 组件，此属性决定是否在输入框获得焦点后自动弹出选项菜单',
        en: 'for non-filterable Select, this prop decides if the option menu pops up when the input is focused',
      },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'clear-icon',
      description: { cn: '自定义清除图标组件', en: 'Custom clear icon component' },
      type: ['string', 'Component'],
      default: 'CircleClose',
      value: [],
    },
    {
      name: 'fit-input-width',
      description: { cn: '下拉框的宽度是否与输入框相同', en: 'whether the width of the dropdown is the same as the input' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'suffix-icon',
      description: { cn: '自定义后缀图标组件', en: 'Custom suffix icon component' },
      type: ['string', 'Component'],
      default: 'ArrowDown',
      value: [],
    },
    {
      name: 'tag-type',
      description: { cn: '标签类型', en: 'tag type' },
      type: 'enum',
      default: 'info',
      value: ['success', 'info', 'warning', 'danger'],
    },
    {
      name: 'validate-event',
      description: { cn: '是否触发表单验证', en: 'whether to trigger form validation' },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'placement',
      description: { cn: '下拉框出现的位置', en: 'position of dropdown' },
      type: 'string',
      default: 'bottom-start',
      value: ['top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left', 'left-start', 'left-end', 'right', 'right-start', 'right-end'],
    },
    {
      name: 'max-collapse-tags',
      description: {
        cn: '需要显示的 Tag 的最大数量 只有当 <code>collapse-tags</code> 设置为 true 时才会生效。(versions >= ^2.3.0)',
        en: 'The max tags number to be shown. To use this, <code>collapse-tags</code> must be true (versions >= ^2.3.0)',
      },
      type: 'number',
      default: '1',
      value: [],
    },
  ],
  events: [
    {
      name: 'change',
      description: { cn: '选中值发生变化时触发', en: 'triggers when the selected value changes' },
      type: 'function',
      param: 'val，目前的选中值',
    },
    {
      name: 'visible-change',
      description: { cn: '下拉框出现/隐藏时触发', en: 'triggers when the dropdown appears/disappears' },
      type: 'function',
      param: 'val，出现则为 true，隐藏则为 false',
    },
    {
      name: 'remove-tag',
      description: { cn: '多选模式下移除tag时触发', en: 'triggers when a tag is removed in multiple mode' },
      type: 'function',
      param: 'val，移除的tag值',
    },
    {
      name: 'clear',
      description: { cn: '可清空的单选模式下用户点击清空按钮时触发', en: 'triggers when the clear icon is clicked in a clearable Select' },
      type: 'function',
      param: '',
    },
    {
      name: 'blur',
      description: { cn: '当 input 失去焦点时触发', en: 'triggers when Input blurs' },
      type: 'function',
      param: '(event: FocusEvent)',
    },
    {
      name: 'focus',
      description: { cn: '当 input 获得焦点时触发', en: 'triggers when Input focuses' },
      type: 'function',
      param: '(event: FocusEvent)',
    },
  ],
  exposes: [
    {
      name: 'focus',
      description: { cn: '使选择器的输入框获取焦点', en: 'focus the Input component' },
      type: 'function',
      param: '',
    },
    {
      name: 'blur',
      description: { cn: '使选择器的输入框失去焦点，并隐藏下拉框', en: 'blur the Input component, and hide the dropdown' },
      type: 'function',
      param: '',
    },
  ],
  slots: [
    {
      name: 'default',
      description: { cn: 'Option 组件列表', en: 'Option component list' },
    },
    {
      name: 'prefix',
      description: { cn: 'Select 组件头部内容', en: 'content as Select prefix' },
    },
    {
      name: 'empty',
      description: { cn: '无选项时的列表', en: 'content when there is no options' },
    },
  ],
};
export default doc;
