import type { TagDoc } from '@/types/tag-doc';
const doc: TagDoc.TagDocInstance = {
  url: 'component/table-v2.html',
  attributes: [
    {
      name: 'cache',
      description: {
        cn: '为了更好的渲染效果预先多加载的行数',
        en: 'Number of rows rendered in advance for boosting the performance',
      },
      type: 'number',
      default: '2',
      value: [],
    },
    {
      name: 'estimated-row-height',
      description: { cn: '渲染动态的单元格的预估高度', en: 'The estimated row height for rendering dynamic height rows' },
      type: 'number',
      default: '-',
      value: [],
    },
    {
      name: 'header-class',
      description: { cn: 'header 部分的自定义 class 名', en: 'Customized class name passed to header wrapper' },
      type: ['string', 'function({ columns, headerIndex })'],
      default: '-',
      value: [],
    },
    {
      name: 'header-props',
      description: { cn: 'header 部分的自定义 props 名', en: 'Customized props name passed to header component' },
      type: ['object', 'function({ columns, headerIndex })'],
      default: '-',
      value: [],
    },
    {
      name: 'header-cell-props',
      description: { cn: 'header 部分的自定义 props 名', en: 'Customized props name passed to header cell component' },
      type: ['object', 'function({ columns, column, columnIndex, headerIndex, style })'],
      default: '-',
      value: [],
    },
    {
      name: 'header-height',
      description: {
        cn: 'header 部分的高度。当传入数组时, 将会渲染和数组长度一样多的 header 行',
        en: "The height of entire header, when it's array, it will render as many header rows as the given array's length",
      },
      type: ['number', 'array'],
      default: '50',
      value: [],
    },
    {
      name: 'footer-height',
      description: {
        cn: 'footer 部分的高度，当传入值时，这部分将被计算入 table 的高度里',
        en: "The height of the footer element, when presented, it will be part of the calculation of the table's height.",
      },
      type: 'number',
      default: '0',
      value: [],
    },
    {
      name: 'row-class',
      description: { cn: 'row wrapper 部分的自定义 class 名', en: 'Customized class name passed to row wrapper' },
      type: ['string', 'function(columns, rowData, rowIndex)'],
      default: '-',
      value: [],
    },
    {
      name: 'row-key',
      description: {
        cn: '每行的 key 值，如果不提供，将使用索引 index 代替',
        en: 'The key of each row, if not provided, it will be the index of the row',
      },
      type: ['string', 'symbol', 'number'],
      default: 'id',
      value: [],
    },
    {
      name: 'row-props',
      description: { cn: 'row component 部分的自定义 class 名', en: 'Customized props name passed to row component' },
      type: ['object', 'function(columns, rowData, rowIndex)'],
      default: '-',
      value: [],
    },
    {
      name: 'row-height',
      description: {
        cn: '每行的高度, 用于计算表的总高度',
        en: 'The height of each row, used for calculating the total height of the table',
      },
      type: 'number',
      default: '50',
      value: [],
    },
    {
      name: 'cell-props',
      description: { cn: '每个单元格 cell 的自定义 props (除了 header cell 以外)', en: 'extra props passed to each cell (except header cells)' },
      type: ['object', 'function(columns, column, columnIndex, headerIndex, style)'],
      default: '-',
      value: [],
    },
    {
      name: 'columns',
      description: { cn: '列 column 的配置数组', en: 'An array of column definitions.' },
      type: 'array',
      default: '-',
      value: [],
    },
    {
      name: 'data',
      description: { cn: '要在表中渲染的数据数组', en: 'An array of data to be rendered in the table.' },
      type: 'array',
      default: '[]',
      value: [],
    },
    {
      name: 'data-getter',
      description: {
        cn: '自定义数据源转换成表格消费的数据格式的处理函数',
        en: 'An method which helps customizing the how to fetch the data from the data source.',
      },
      type: 'function',
      default: '-',
      value: [],
    },
    {
      name: 'fixed-data',
      description: {
        cn: '渲染行在表格主内容上方和 header 下方区域的数据',
        en: 'Data for rendering rows above the main content and below the header',
      },
      type: 'array',
      default: '-',
      value: [],
    },
    {
      name: 'expand-column-key',
      description: { cn: '列的 key 来标记哪个行可以被展开', en: 'The column key indicates which row is expandable' },
      type: 'string',
      default: '-',
      value: [],
    },
    {
      name: 'expanded-row-keys',
      description: {
        cn: '存放行展开状态的 key 的数组，可以和 `v-model` 搭配使用',
        en: 'An array of keys for expanded rows, can be used with &#60;code&#62;v-model&#60;/code&#62;',
      },
      type: 'array',
      default: '-',
      value: [],
    },
    {
      name: 'default-expanded-row-keys',
      description: {
        cn: '默认展开的行的 key 的数组, 这个数据不是响应式的',
        en: 'An array of keys for default expanded rows, &#60;strong&#62;NON REACTIVE&#60;/strong&#62;',
      },
      type: 'array',
      default: '-',
      value: [],
    },
    {
      name: 'class',
      description: {
        cn: '表格的类名称，将应用于表格的全部的三个部分 (左、右、主)',
        en: 'Class name for the the virtual table, will be applied to all three tables (left, right, main)',
      },
      type: ['string', 'array', 'object'],
      default: '-',
      value: [],
    },
    {
      name: 'fixed',
      description: {
        cn: '单元格宽度是自适应还是固定',
        en: "Flag indicates the table column's width is a fixed or flexible.",
      },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'width',
      description: { cn: '表的宽度，必填', en: 'Width for the table, required' },
      type: 'number',
      default: '-',
      value: [],
    },
    {
      name: 'height',
      description: { cn: '表的高度，必填', en: 'Height for the table, required' },
      type: 'number',
      default: '-',
      value: [],
    },
    {
      name: 'max-height',
      description: { cn: '表格的最大高度', en: 'Maximum height for the table' },
      type: 'number',
      default: '-',
      value: [],
    },
    {
      name: 'h-scrollbar-size',
      description: {
        cn: '配置表格的水平滚动条大小，防止水平和垂直滚动条重叠。',
        en: "Indicates the horizontal scrollbar's size for the table, used to prevent the horizontal and vertical scrollbar to collapse",
      },
      type: 'number',
      default: '6',
      value: [],
    },
    {
      name: 'v-scrollbar-size',
      description: {
        cn: '配置表格的垂直滚动条大小，防止水平和垂直滚动条重叠。',
        en: "Indicates the vertical scrollbar's size for the table, used to prevent the horizontal and vertical scrollbar to collapse",
      },
      type: 'number',
      default: '6',
      value: [],
    },
    {
      name: 'scrollbar-always-on',
      description: {
        cn: '如果开启，滚动条将一直显示，反之只会在鼠标经过时显示。',
        en: 'If true, the scrollbar will always be shown instead of when mouse is placed above the table',
      },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'sort-by',
      description: { cn: '排序方式', en: 'Sort indicator' },
      type: 'object',
      default: '{}',
      value: [],
    },
    {
      name: 'sort-state',
      description: { cn: '多个排序', en: 'Multiple sort indicator' },
      type: 'object',
      default: '',
      value: [],
    },
  ],
  events: [
    {
      name: 'column-sort',
      description: { cn: '列排序时调用', en: 'Invoked when column sorted' },
      type: 'function',
      param: 'Object&#60;ColumnSortParam&#62;',
    },
    {
      name: 'expanded-rows-change',
      description: { cn: '行展开状态改变时触发', en: 'Invoked when expanded rows changed' },
      type: 'function',
      param: '',
    },
    {
      name: 'end-reached',
      description: { cn: '到达表格末尾时触发', en: 'Invoked when the end of the table is reached' },
      type: 'function',
      param: 'Array&#60;KeyType&#62;',
    },
    {
      name: 'scroll',
      description: { cn: '表格被用户滚动后触发', en: 'Invoked after scrolled' },
      type: 'function',
      param: 'Object&#60;ScrollParams&#62;',
    },
    {
      name: 'rows-rendered',
      description: { cn: '当行被渲染后触发', en: 'Invoked when rows are rendered' },
      type: 'function',
      param: 'Object&#60;RowsRenderedParams&#62;',
    },
    {
      name: 'row-expand',
      description: {
        cn: '点击箭头图标展开/折叠树节点时触发',
        en: 'Invoked when expand/collapse the tree node by clicking the arrow icon',
      },
      type: 'function',
      param: 'Object&#60;RowExpandParams&#62;',
    },
    {
      name: 'row-event-handlers',
      description: { cn: '当每行添加了一系列事件处理器时触发', en: 'A collection of handlers attached to each row' },
      type: 'function',
      param: 'Object&#60;RowEventHandlers&#62;',
    },
  ],
  exposes: [
    {
      name: 'scrollTo',
      description: { cn: '滚动到给定位置', en: 'Scroll to a given position' },
      type: 'function',
      param: '{ scrollLeft?: number, scrollTop?: number}',
    },
    {
      name: 'scrollToLeft',
      description: { cn: '滚动到给定的水平位置', en: 'Scroll to a given horizontal position' },
      type: 'function',
      param: 'scrollTop: number',
    },
    {
      name: 'scrollToTop',
      description: { cn: '滚动到给定的垂直位置', en: 'Scroll to a given vertical position' },
      type: 'function',
      param: 'scrollLeft: number',
    },
    {
      name: 'scrollToRow',
      description: { cn: '使用给定的滚动策略滚动至指定行', en: 'scroll to a given row with specified scroll strategy' },
      type: 'function',
      param: 'row: number, strategy?: "auto" | "center" | "end" | "start" | "smart"',
    },
  ],
  slots: [
    {
      name: 'cell',
      description: { cn: '-', en: '-' },
    },
    {
      name: 'header',
      description: { cn: '-', en: '-' },
    },
    {
      name: 'header-cell',
      description: { cn: '-', en: '-' },
    },
    {
      name: 'row',
      description: { cn: '-', en: '-' },
    },
    {
      name: 'footer',
      description: { cn: '', en: '-' },
    },
    {
      name: 'empty',
      description: { cn: '', en: '-' },
    },
    {
      name: 'overlay',
      description: { cn: '', en: '-' },
    },
  ],
  childAttributes: [
    {
      name: 'Column',
      list: [
        {
          name: 'overlay',
          description: { cn: '表格单元格内容对齐方式', en: 'Alignment of the table cell content' },
          type: 'enum',
          default: '',
          value: ['center', 'right'],
        },
        {
          name: 'class',
          description: { cn: '列的类名', en: 'Class name for the column' },
          type: 'string',
          default: '',
          value: [],
        },
        {
          name: 'fixed',
          description: { cn: '固定列位置', en: 'Fixed direction of the column' },
          type: ['enum', 'boolean'],
          default: '',
          value: ['left', 'right', 'true', 'false'],
        },
        {
          name: 'flexGrow',
          description: { cn: 'CSS 属性 flex grow, 仅当不是固定表时才生效', en: 'CSSProperties flex grow, Only useful when not this is not a fixed table' },
          type: 'number',
          default: '0',
          value: [],
        },
        {
          name: 'flexShrink',
          description: { cn: 'CSS 属性 flex shrink, 仅当不是固定表时才生效', en: 'CSSProperties flex shrink, Only useful when not this is not a fixed table' },
          type: 'number',
          default: '1',
          value: [],
        },
        {
          name: 'headerClass',
          description: { cn: '自定义 header 头部类名', en: 'Used for customizing header column class' },
          type: 'string',
          default: '',
          value: [],
        },
        {
          name: 'hidden',
          description: { cn: '此列是否不可见', en: 'Whether the column is invisible' },
          type: 'boolean',
          default: '',
          value: [],
        },
        {
          name: 'style',
          description: { cn: '自定义列单元格的类名，将会与 gird 单元格合并', en: 'Customized style for column cell, will be merged with grid cell' },
          type: ['string', 'object', 'array'],
          default: '',
          value: [],
        },
        {
          name: 'sortable',
          description: { cn: '设置列是否可排序', en: 'Indicates whether the column is sortable' },
          type: 'boolean',
          default: '',
          value: [],
        },
        {
          name: 'title',
          description: { cn: 'Header 头部单元格中的默认文本', en: 'The default text rendered in header cell' },
          type: 'string',
          default: '',
          value: [],
        },
        {
          name: 'maxWidth',
          description: { cn: '列的最大宽度', en: 'Maximum width for the column' },
          type: 'string',
          default: '',
          value: [],
        },
        {
          name: 'minWidth',
          description: { cn: '列的最小宽度', en: 'Minimum width for the column' },
          type: 'string',
          default: '',
          value: [],
        },
        {
          name: 'width',
          description: { cn: '列的宽度 必填', en: 'Width for the column Required' },
          type: 'number',
          default: '',
          value: [],
        },
        {
          name: 'cellRenderer',
          description: { cn: '自定义单元格渲染器', en: 'Customized Cell renderer' },
          type: ['Component', 'function'],
          default: '',
          value: [],
        },
        {
          name: 'headerCellRenderer',
          description: { cn: '自定义头部渲染器', en: 'Customized Header renderer' },
          type: ['Component', 'function'],
          default: '',
          value: [],
        },
      ],
    },
  ],
};
export default doc;
