import type { TagDoc } from '@/types/tag-doc';
const doc: TagDoc.TagDocInstance = {
  url: 'component/table.html',
  attributes: [
    {
      name: 'data',
      description: { cn: '显示的数据', en: 'Table data' },
      type: 'array',
      default: '—',
      value: [],
    },
    {
      name: 'height',
      description: {
        cn: 'Table 的高度， 默认为自动高度。 如果 height 为 number 类型，单位 px；如果 height 为 string 类型，则这个高度会设置为 Table 的 style.height 的值，Table 的高度会受控于外部样式。',
        en: "Table's height. By default it has an <code>auto</code> height. If its value is a number, the height is measured in pixels; if its value is a string, the value will be assigned to element's style.height, the height is affected by external styles",
      },
      type: ['string', 'number'],
      default: '—',
      value: [],
    },
    {
      name: 'max-height',
      description: {
        cn: 'Table 的最大高度。 合法的值为数字或者单位为 px 的高度。',
        en: "Table's max-height. The legal value is a number or the height in px.",
      },
      type: ['string', 'number'],
      default: '—',
      value: [],
    },
    {
      name: 'stripe',
      description: { cn: '是否为斑马纹 table', en: 'whether Table is striped' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'border',
      description: { cn: '是否带有纵向边框', en: 'whether Table has vertical border' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'size',
      description: { cn: 'Table 的尺寸', en: 'size of Table' },
      type: 'enum',
      default: '—',
      value: [`large`, `default`, `small`],
    },
    {
      name: 'fit',
      description: { cn: '列的宽度是否自撑开', en: 'whether width of column automatically fits its container' },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'show-header',
      description: { cn: '是否显示表头', en: 'whether Table header is visible' },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'highlight-current-row',
      description: { cn: '是否要高亮当前行', en: 'whether current row is highlighted' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'current-row-key',
      description: { cn: '当前行的 key，只写属性', en: 'key of current row, a set only prop' },
      type: ['string', 'number'],
      default: '—',
      value: [],
    },
    {
      name: 'row-class-name',
      description: {
        cn: '行的 className 的回调方法，也可以使用字符串为所有行设置一个固定的 className。',
        en: 'function that returns custom class names for a row, or a string assigning class names for every row',
      },
      type: ['string', 'function({ row, rowindex })'],
      default: '—',
      value: [],
    },
    {
      name: 'row-style',
      description: {
        cn: '行的 style 的回调方法，也可以使用一个固定的 Object 为所有行设置一样的 Style。',
        en: 'function that returns custom style for a row, or an object assigning custom style for every row',
      },
      type: ['object', 'function({ row, rowIndex })'],
      default: '—',
      value: [],
    },
    {
      name: 'cell-class-name',
      description: {
        cn: '单元格的 className 的回调方法，也可以使用字符串为所有单元格设置一个固定的 className。',
        en: 'function that returns custom class names for a cell, or a string assigning class names for every cell',
      },
      type: ['string', 'function({ row, column, rowIndex, columnIndex })'],
      default: '—',
      value: [],
    },
    {
      name: 'cell-style',
      description: {
        cn: '单元格的 className 的回调方法，也可以使用字符串为所有单元格设置一个固定的 className。',
        en: 'function that returns custom style for a cell, or an object assigning custom style for every cell',
      },
      type: ['string', 'function({ row, column, rowIndex, columnIndex })'],
      default: '—',
      value: [],
    },
    {
      name: 'header-row-class-name',
      description: {
        cn: '单元格的 className 的回调方法，也可以使用字符串为所有单元格设置一个固定的 className。',
        en: 'function that returns custom class names for a row in table header, or a string assigning class names for every row in table header',
      },
      type: ['string', 'function({ row, rowIndex })'],
      default: '—',
      value: [],
    },
    {
      name: 'header-row-style',
      description: {
        cn: '表头行的 style 的回调方法，也可以使用一个固定的 Object 为所有表头行设置一样的 Style。',
        en: 'function that returns custom style for a row in table header, or an object assigning custom style for every row in table header',
      },
      type: ['object', 'function({ row, rowIndex })'],
      default: '—',
      value: [],
    },
    {
      name: 'header-cell-class-name',
      description: {
        cn: '表头单元格的 className 的回调方法，也可以使用字符串为所有表头单元格设置一个固定的 className。',
        en: 'function that returns custom class names for a cell in table header, or a string assigning class names for every cell in table header',
      },
      type: ['string', 'function({ row, column, rowIndex, columnIndex })'],
      default: '—',
      value: [],
    },
    {
      name: 'header-cell-style',
      description: {
        cn: '表头单元格的 style 的回调方法，也可以使用一个固定的 Object 为所有表头单元格设置一样的 Style。',
        en: 'function that returns custom style for a cell in table header, or an object assigning custom style for every cell in table header',
      },
      type: ['object', 'function({ row, column, rowIndex, columnIndex })'],
      default: '—',
      value: [],
    },
    {
      name: 'row-key',
      description: {
        cn: '行数据的 Key，用来优化 Table 的渲染； 在使用`reserve-selection`功能与显示树形数据时，该属性是必填的。 类型为 String 时，支持多层访问：`user.info.id` ，但不支持 `user.info[0].id` ，此种情况请使用 `function` 。',
        en: 'key of row data, used for optimizing rendering. Required if <code>reserve-selection</code> is on or display tree data. When its type is String, multi-level access is supported, e.g. <code>user.info.id</code>, but <code>user.info[0].id</code> is not supported, in which case <code>Function</code> should be used.',
      },
      type: ['string', 'function(row)'],
      default: '—',
      value: [],
    },
    {
      name: 'empty-text',
      description: {
        cn: '空数据时显示的文本内容， 也可以通过 <code>#empty</code> 设置',
        en: 'Displayed text when data is empty. You can customize this area with <code>#empty</code>',
      },
      type: 'string',
      default: 'No Data',
      value: [],
    },
    {
      name: 'default-expand-all',
      description: {
        cn: '是否默认展开所有行，当 Table 包含展开行存在或者为树形表格时有效',
        en: 'whether expand all rows by default, works when the table has a column type="expand" or contains tree structure data',
      },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'expand-row-keys',
      description: {
        cn: '可以通过该属性设置 Table 目前的展开行，需要设置 row-key 属性才能使用，该属性为展开行的 keys 数组。',
        en: "set expanded rows by this prop, prop's value is the keys of expand rows, you should set row-key before using this prop",
      },
      type: 'array',
      default: '—',
      value: [],
    },
    {
      name: 'default-sort',
      description: {
        cn: '默认的排序列的 prop 和顺序。 它的 `prop` 属性指定默认的排序的列，`order` 指定默认排序的顺序,`order`的可选值为`ascending`或`descending`. 如果只指定了 prop, 没有指定 order, 则默认顺序是 ascending',
        en: 'set the default sort column and order. property `prop` is used to set default sort column, property `order` is used to set default sort order.The optional value of `order` is `ascending` or `descending`, if `prop` is set, and order is not set, then order is default to ascending',
      },
      type: 'object',
      default: '—',
      value: [],
    },
    {
      name: 'tooltip-effect',
      description: { cn: '溢出的 tooltip 的 <code>effect</code>', en: 'the <code>effect</code> of the overflow tooltip' },
      type: 'enum',
      default: 'light',
      value: ['dark', 'light'],
    },
    {
      name: 'tooltip-options',
      description: {
        cn: '溢出 tooltip 的选项，参见 `el-tooltip` 组件',
        en: 'the options for the overflow tooltip, see the `el-tooltip` component',
      },
      type: 'object',
      default: "{ enterable: true, placement: 'top', showArrow: true, hideAfter: 200, popperOptions: { strategy: 'fixed' } }",
      value: [],
    },
    {
      name: 'show-summary',
      description: { cn: '是否在表尾显示合计行', en: 'whether to display a summary row' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'sum-text',
      description: { cn: '显示摘要行第一列的文本', en: 'displayed text for the first column of summary row' },
      type: 'string',
      default: 'Sum',
      value: [],
    },
    {
      name: 'summary-method',
      description: { cn: '自定义的合计计算方法', en: 'custom summary method' },
      type: 'function({ columns, data })',
      default: '—',
      value: [],
    },
    {
      name: 'span-method',
      description: { cn: '合并行或列的计算方法', en: 'method that returns rowspan and colspan' },
      type: 'function({ row, column, rowindex, columnindex })',
      default: '—',
      value: [],
    },
    {
      name: 'select-on-indeterminate',
      description: {
        cn: '在多选表格中，当仅有部分行被选中时，点击表头的多选框时的行为。 若为 true，则选中所有行；若为 false，则取消选择所有行',
        en: 'controls the behavior of master checkbox in multi-select tables when only some rows are selected (but not all). If true, all rows will be selected, else deselected.',
      },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'indent',
      description: { cn: '展示树形数据时，树节点的缩进', en: 'horizontal indentation of tree data' },
      type: 'number',
      default: '16',
      value: [],
    },
    {
      name: 'lazy',
      description: { cn: '是否懒加载子节点数据', en: 'whether to lazy loading data' },
      type: 'boolean',
      default: '—',
      value: [],
    },
    {
      name: 'load',
      description: {
        cn: '加载子节点数据的函数，<code>lazy</code> 为 true 时生效',
        en: 'method for loading child row data, only works when <code>lazy</code> is true',
      },
      type: 'function(row, treenode, resolve)',
      default: '—',
      value: [],
    },
    {
      name: 'tree-props',
      description: { cn: '渲染嵌套数据的配置选项', en: 'configuration for rendering nested data' },
      type: 'object',
      default: "{ hasChildren: 'hasChildren', children: 'children' }",
      value: [],
    },
    {
      name: 'table-layout',
      description: {
        cn: '设置表格单元、行和列的布局方式',
        en: 'Sets the algorithm used to lay out table cells, rows, and columns',
      },
      type: 'string',
      default: 'fixed',
      value: [],
    },
    {
      name: 'scrollbar-always-on',
      description: { cn: '总是显示滚动条', en: 'always show scrollbar' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'flexible',
      description: { cn: '确保主轴的最小尺寸', en: "ensure main axis minimum-size doesn't follow the content" },
      type: 'boolean',
      default: 'false',
      value: [],
    },
  ],
  events: [
    {
      name: 'select',
      description: { cn: '当用户手动勾选数据行的 Checkbox 时触发的事件', en: 'triggers when user clicks the checkbox in a row' },
      type: 'function',
      param: 'selection, row',
    },
    {
      name: 'select-all',
      description: { cn: 'triggers when user clicks the checkbox in table header', en: 'triggers when user clicks the checkbox in table header' },
      type: 'function',
      param: 'selection',
    },
    {
      name: 'selection-change',
      description: { cn: 'triggers when selection changes', en: 'triggers when selection changes' },
      type: 'function',
      param: 'selection',
    },
    {
      name: 'cell-mouse-enter',
      description: { cn: 'triggers when hovering into a cell', en: 'triggers when hovering into a cell' },
      type: 'function',
      param: 'row, column, cell, event',
    },
    {
      name: 'cell-mouse-leave',
      description: { cn: 'triggers when hovering out of a cell', en: 'triggers when hovering out of a cell' },
      type: 'function',
      param: 'row, column, cell, event',
    },
    {
      name: 'cell-click',
      description: { cn: 'triggers when clicking a cell', en: 'triggers when clicking a cell' },
      type: 'function',
      param: 'row, column, cell, event',
    },
    {
      name: 'cell-dblclick',
      description: { cn: 'triggers when double clicking a cell', en: 'triggers when double clicking a cell' },
      type: 'function',
      param: 'row, column, cell, event',
    },
    {
      name: 'cell-contextmenu',
      description: { cn: 'triggers when user right clicks on a cell', en: 'triggers when user right clicks on a cell' },
      type: 'function',
      param: 'row, column, cell, event',
    },
    {
      name: 'row-click',
      description: { cn: 'triggers when clicking a row', en: 'triggers when clicking a row' },
      type: 'function',
      param: 'row, column, event',
    },
    {
      name: 'row-contextmenu',
      description: { cn: 'triggers when user right clicks on a row', en: 'triggers when user right clicks on a row' },
      type: 'function',
      param: 'row, column, event',
    },
    {
      name: 'row-dblclick',
      description: { cn: 'triggers when double clicking a row', en: 'triggers when double clicking a row' },
      type: 'function',
      param: 'row, column, event',
    },
    {
      name: 'header-click',
      description: { cn: 'triggers when clicking a column header', en: 'triggers when clicking a column header' },
      type: 'function',
      param: 'column, event',
    },
    {
      name: 'header-contextmenu',
      description: { cn: 'triggers when user right clicks on a column header', en: 'triggers when user right clicks on a column header' },
      type: 'function',
      param: 'column, event',
    },
    {
      name: 'sort-change',
      description: { cn: "triggers when Table's sorting changes", en: "triggers when Table's sorting changes" },
      type: 'function',
      param: '{ column, prop, order }',
    },
    {
      name: 'filter-change',
      description: {
        cn: "column's key. If you need to use the filter-change event, this attribute is mandatory to identify which column is being filtered",
        en: "column's key. If you need to use the filter-change event, this attribute is mandatory to identify which column is being filtered",
      },
      type: 'function',
      param: 'filters',
    },
    {
      name: 'current-change',
      description: { cn: 'triggers when current row changes', en: 'triggers when current row changes' },
      type: 'function',
      param: 'currentRow, oldCurrentRow',
    },
    {
      name: 'header-dragend',
      description: {
        cn: "triggers after changing a column's width by dragging the column header's border",
        en: "triggers after changing a column's width by dragging the column header's border",
      },
      type: 'function',
      param: 'newWidth, oldWidth, column, event',
    },
    {
      name: 'expand-change',
      description: {
        cn: 'triggers when user expands or collapses a row (for expandable table, second param is expandedRows; for tree Table, second param is expanded)',
        en: 'triggers when user expands or collapses a row (for expandable table, second param is expandedRows; for tree Table, second param is expanded)',
      },
      type: 'function',
      param: 'row, (expandedRows / expanded)',
    },
  ],
  exposes: [
    {
      name: 'clearSelection',
      description: { cn: '用于多选表格，清空用户的选择', en: 'used in multiple selection Table, clear user selection' },
      type: 'function',
      param: '',
    },
    {
      name: 'getSelectionRows',
      description: { cn: '返回当前选中的行', en: 'returns the currently selected rows' },
      type: 'function',
      param: '',
    },
    {
      name: 'toggleRowSelection',
      description: {
        cn: '用于多选表格，切换某一行的选中状态， 如果使用了第二个参数，则可直接设置这一行选中与否',
        en: 'used in multiple selection Table, toggle if a certain row is selected. With the second parameter, you can directly set if this row is selected',
      },
      type: 'function',
      param: 'row, selected',
    },
    {
      name: 'toggleAllSelection',
      description: {
        cn: '用于多选表格，切换全选和全不选',
        en: 'used in multiple selection Table, toggle select all and deselect all',
      },
      type: 'function',
      param: '',
    },
    {
      name: 'toggleRowExpansion',
      description: {
        cn: '用于可扩展的表格或树表格，如果某行被扩展，则切换。 使用第二个参数，您可以直接设置该行应该被扩展或折叠。',
        en: 'used in expandable Table or tree Table, toggle if a certain row is expanded. With the second parameter, you can directly set if this row is expanded or collapsed',
      },
      type: 'function',
      param: 'row, expanded',
    },
    {
      name: 'setCurrentRow',
      description: {
        cn: '用于单选表格，设定某一行为选中行， 如果调用时不加参数，则会取消目前高亮行的选中状态。',
        en: 'used in single selection Table, set a certain row selected. If called without any parameter, it will clear selection.',
      },
      type: 'function',
      param: 'row',
    },
    {
      name: 'clearSort',
      description: { cn: '用于清空排序条件，数据会恢复成未排序的状态', en: 'clear sorting, restore data to the original order' },
      type: 'function',
      param: '',
    },
    {
      name: 'clearFilter',
      description: {
        cn: '传入由 <code>columnKey</code> 组成的数组以清除指定列的过滤条件。 如果没有参数，清除所有过滤器',
        en: 'clear filters of the columns whose <code>columnKey</code> are passed in. If no params, clear all filters',
      },
      type: 'function',
      param: 'columnKeys',
    },
    {
      name: 'doLayout',
      description: {
        cn: '对 Table 进行重新布局。 当表格可见性变化时，您可能需要调用此方法以获得正确的布局',
        en: 'refresh the layout of Table. When the visibility of Table changes, you may need to call this method to get a correct layout',
      },
      type: 'function',
      param: '',
    },
    {
      name: 'sort',
      description: {
        cn: '手动排序表格。 参数 <code>prop</code> 属性指定排序列， <code>order</code> 指定排序顺序。',
        en: 'sort Table manually. Property <code>prop</code> is used to set sort column, property <code>order</code> is used to set sort order',
      },
      type: 'function',
      param: 'prop: string, order: string',
    },
    {
      name: 'scrollTo',
      description: { cn: '滚动到一组特定坐标', en: 'scrolls to a particular set of coordinates' },
      type: 'function',
      param: '(options: ScrollToOptions | number, yCoord?: number)',
    },
    {
      name: 'setScrollTop',
      description: { cn: '设置垂直滚动位置', en: 'set vertical scroll position' },
      type: 'function',
      param: 'top',
    },
    {
      name: 'setScrollLeft',
      description: { cn: '设置水平滚动位置', en: 'set horizontal scroll position' },
      type: 'function',
      param: 'left',
    },
  ],
  slots: [
    {
      name: 'default',
      description: { cn: '自定义默认内容', en: 'customize default content' },
    },
    {
      name: 'append',
      description: {
        cn: '插入至表格最后一行之后的内容， 如果需要对表格的内容进行无限滚动操作，可能需要用到这个 slot。 若表格有合计行，该 slot 会位于合计行之上。',
        en: 'Contents to be inserted after the last row. You may need this slot if you want to implement infinite scroll for the table. This slot will be displayed above the summary row if there is one.',
      },
    },
    {
      name: 'empty',
      description: { cn: '当数据为空时自定义的内容', en: 'you can customize content when data is empty.' },
    },
  ],
};
export default doc;
