import type { TagDoc } from '@/types/tag-doc';
const doc: TagDoc.TagDocInstance = {
  url: 'component/time-picker.html',
  attributes: [
    {
      name: 'v-model',
      description: { cn: '绑定值，如果它是数组，长度应该是 2', en: 'binding value, if it is an array, the length should be 2' },
      type: ['Date', 'number', 'string', 'array'],
      default: '—',
      value: [],
    },
    {
      name: 'readonly',
      description: { cn: '完全只读', en: 'whether TimePicker is read only' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'disabled',
      description: { cn: '是否禁用', en: 'whether TimePicker is disabled' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'editable',
      description: { cn: '文本框可输入', en: 'whether the input is editable' },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'clearable',
      description: { cn: '是否显示清除按钮', en: 'whether to show clear button' },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'size',
      description: { cn: '输入框尺寸', en: 'size of Input' },
      type: 'enum',
      default: '—',
      value: ['large', 'default', 'small'],
    },
    {
      name: 'placeholder',
      description: { cn: '非范围选择时的占位内容', en: 'placeholder in non-range mode' },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'start-placeholder',
      description: { cn: '范围选择时开始日期的占位内容', en: 'placeholder for the start time in range mode' },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'end-placeholder',
      description: { cn: '范围选择时结束日期的占位内容', en: 'placeholder for the end time in range mode' },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'is-range',
      description: { cn: '是否为时间范围选择', en: 'whether to pick a time range' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'arrow-control',
      description: { cn: '是否使用箭头进行时间选择', en: 'whether to pick time using arrow buttons' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'popper-class',
      description: { cn: 'TimePicker 下拉框的类名', en: "custom class name for TimePicker's dropdown" },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'range-separator',
      description: { cn: '选择范围时的分隔符', en: 'range separator' },
      type: 'string',
      default: "'-'",
      value: [],
    },
    {
      name: 'format',
      description: {
        cn: '显示在输入框中的格式，详见[格式表示](https://day.js.org/docs/en/display/format#list-of-all-available-formats)',
        en: 'format of the displayed value in the input box， see more at [formats](https://day.js.org/docs/en/display/format#list-of-all-available-formats)',
      },
      type: 'string',
      default: 'HH:mm:ss',
      value: [],
    },
    {
      name: 'default-value',
      description: { cn: '可选，选择器打开时默认显示的时间,如果它是数组，长度应该是 2', en: 'optional, default date of the calendar,the length should be 2' },
      type: ['Date', '[Date, Date]'],
      default: '—',
      value: [],
    },
    {
      name: 'id',
      description: { cn: '等价于原生 input `id` 属性', en: 'same as `id` in native input' },
      type: ['string', '[string, string]'],
      default: '-',
      value: [],
    },
    {
      name: 'name',
      description: { cn: '等价于原生 input `name` 属性', en: 'same as `name` in native input' },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'prefix-icon',
      description: { cn: '自定义前缀图标', en: 'Custom prefix icon component' },
      type: ['string', 'Component'],
      default: 'Clock',
      value: [],
    },
    {
      name: 'clear-icon',
      description: { cn: '自定义清除图标', en: 'Custom clear icon component' },
      type: ['string', 'Component'],
      default: 'CircleClose',
      value: [],
    },
    {
      name: 'disabled-hours',
      description: { cn: '禁止选择部分小时选项', en: 'To specify the array of hours that cannot be selected' },
      type: 'function',
      default: '—',
      value: [],
    },
    {
      name: 'disabled-minutes',
      description: { cn: '禁止选择部分分钟选项', en: 'To specify the array of minutes that cannot be selected' },
      type: 'function(selectedhour)',
      default: '—',
      value: [],
    },
    {
      name: 'disabled-seconds',
      description: { cn: '禁止选择部分秒选项', en: 'To specify the array of seconds that cannot be selected' },
      type: 'function(selectedhour, selectedminute)',
      default: '—',
      value: [],
    },
    {
      name: 'teleported',
      description: { cn: '是否将 popover 的下拉列表镜像至 body 元素', en: 'whether time-picker dropdown is teleported to the body' },
      type: 'boolean',
      default: 'true',
      value: [],
    },
  ],
  events: [
    {
      name: 'change',
      description: { cn: '用户确认选定的值时触发', en: 'triggers when user confirms the value' },
      type: 'function',
      param: '(val: typeof v-model)',
    },
    {
      name: 'blur',
      description: { cn: '在组件 Input 失去焦点时触发', en: 'triggers when Input blurs' },
      type: 'function',
      param: '(e: FocusEvent)',
    },
    {
      name: 'focus',
      description: { cn: '在组件 Input 获得焦点时触发', en: 'triggers when Input focuses' },
      type: 'function',
      param: '(e: FocusEvent)',
    },
    {
      name: 'visible-change',
      description: { cn: '当 TimePicker 的下拉列表出现/消失时触发', en: "triggers when the TimePicker's dropdown appears/disappears" },
      type: 'function',
      param: '(visibility: boolean)',
    },
  ],
  exposes: [
    {
      name: 'focus',
      description: { cn: '使 input 获取焦点', en: 'focus the Input component' },
      type: 'function',
      param: '',
    },
    {
      name: 'blur',
      description: { cn: '使 input 失去焦点', en: 'blur the Input component' },
      type: 'function',
      param: '',
    },
    {
      name: 'handleOpen',
      description: { cn: '打开时间选择器弹窗', en: 'open the TimePicker popper' },
      type: 'function',
      param: '',
    },
    {
      name: 'handleClose',
      description: { cn: '关闭时间选择器弹窗', en: 'close the TimePicker popper' },
      type: 'function',
      param: '',
    },
  ],
};
export default doc;
