import type { TagDoc } from '@/types/tag-doc';
const doc: TagDoc.TagDocInstance = {
  url: 'component/tooltip.html',
  attributes: [
    {
      name: 'append-to',
      description: {
        cn: '指示 Tooltip 的内容将附加在哪一个网页元素上,类型为一个dom元素或者一个css选择器如id或者class',
        en: 'which element the tooltip CONTENT appends to',
      },
      type: ['CSSSelector', 'HTMLElement'],
      default: '—',
      value: ['HTMLElement'],
    },
    {
      name: 'effect',
      description: {
        cn: 'Tooltip 主题，内置了<code>dark</code> / <code>light</code> 两种',
        en: 'Tooltip theme, built-in theme: <code>dark</code> / <code>light</code>',
      },
      type: 'enum',
      default: "'light'",
      value: ['dark', 'light'],
    },
    {
      name: 'content',
      description: {
        cn: '显示的内容，也可被`content`插槽覆盖覆盖',
        en: 'display content, can be overridden by <code>slot#content</code>',
      },
      type: 'string',
      default: "''",
      value: [],
    },
    {
      name: 'raw-content',
      description: { cn: '`content` 中的内容是否作为 HTML 字符串处理', en: 'whether <code>content</code> is treated as HTML string' },
      type: 'boolean',
      default: 'false',
      value: [],
    },
    {
      name: 'placement',
      description: { cn: 'Tooltip 组件出现的位置', en: 'position of Tooltip' },
      type: 'enum',
      default: "'top-start'",
      value: ['top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left', 'left-start', 'left-end', 'right', 'right-start', 'right-end'],
    },
    {
      name: 'visible',
      description: { cn: 'Tooltip 组件可见性,支持双向绑定(`v-model:visible`)', en: 'visibility of Tooltip (support `v-model:visible`)' },
      type: 'boolean',
      default: '—',
      value: [],
    },
    {
      name: 'disabled',
      description: { cn: 'Tooltip 组件是否禁用', en: 'whether Tooltip is disabled' },
      type: 'boolean',
      default: '—',
      value: [],
    },
    {
      name: 'offset',
      description: { cn: '出现位置的偏移量', en: 'offset of the Tooltip' },
      type: 'number',
      default: '12',
      value: [],
    },
    {
      name: 'transition',
      description: { cn: '动画名称', en: 'animation name' },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'popper-options',
      description: {
        cn: '请参考：<a href="https://popper.js.org/docs/v2/">popper.js</a>的参数',
        en: '<a href="https://popper.js.org/docs/v2/">popper.js</a> parameters',
      },
      type: 'object',
      default: '{}',
      value: [],
    },
    {
      name: 'show-after',
      description: { cn: '在触发后多久显示内容，单位毫秒', en: 'delay of appearance, in millisecond' },
      type: 'number',
      default: '0',
      value: [],
    },
    {
      name: 'show-arrow',
      description: { cn: 'tooltip 的内容是否有箭头', en: 'whether the tooltip content has an arrow' },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'hide-after',
      description: { cn: '延迟关闭，单位毫秒', en: 'delay of disappear, in millisecond' },
      type: 'number',
      default: '200',
      value: [],
    },
    {
      name: 'auto-close',
      description: { cn: 'tooltip 出现后自动隐藏延时，单位毫秒', en: 'timeout in milliseconds to hide tooltip' },
      type: 'number',
      default: '0',
      value: [],
    },
    {
      name: 'popper-class',
      description: { cn: '为 Tooltip 的 popper 添加类名', en: "custom class name for Tooltip's popper" },
      type: 'string',
      default: '—',
      value: [],
    },
    {
      name: 'enterable',
      description: { cn: '鼠标是否可进入到 tooltip 中', en: 'whether the mouse can enter the tooltip' },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'teleported',
      description: {
        cn: '是否使用 teleport。设置成 `true` 则会被追加到 `append-to` 的位置',
        en: 'whether tooltip content is teleported, if <code>true</code> it will be teleported to where <code>append-to</code> sets',
      },
      type: 'boolean',
      default: 'true',
      value: [],
    },
    {
      name: 'trigger',
      description: { cn: '如何触发 Tooltip', en: 'How should the tooltip be triggered (to show)' },
      type: 'enum',
      default: "'hover'",
      value: ['hover', 'click', 'focus', 'contextmenu'],
    },
    {
      name: 'virtual-triggering',
      description: { cn: '用来标识虚拟触发是否被启用', en: 'Indicates whether virtual triggering is enabled' },
      type: 'boolean',
      default: '—',
      value: [],
    },
    {
      name: 'virtual-ref',
      description: {
        cn: '标识虚拟触发时的触发元素',
        en: 'Indicates the reference element to which the tooltip is attached',
      },
      type: 'HTMLElement',
      default: '—',
      value: [],
    },
    {
      name: 'trigger-keys',
      description: {
        cn: '当鼠标点击或者聚焦在触发元素上时， 可以定义一组键盘按键并且通过它们来控制 Tooltip 的显示',
        en: 'When you click the mouse to focus on the trigger element, you can define a set of keyboard codes to control the display of tooltip through the keyboard',
      },
      type: 'array',
      default: "['Enter','Space']",
      value: [],
    },
    {
      name: 'persistent',
      description: {
        cn: '当 tooltip 组件长时间不触发且 `persistent` 属性设置为 `false` 时, popconfirm 将会被删除',
        en: 'when tooltip inactive and <code>persistent</code> is <code>false</code> , popconfirm will be destroyed',
      },
      type: 'boolean',
      default: '—',
      value: [],
    },
    {
      name: 'aria-label',
      description: { cn: '和 原生 `aria-label` 属性保持一致，用于无障碍访问', en: 'same as <code>aria-label</code>' },
      type: 'string',
      default: '—',
      value: [],
    },
  ],
  exposes: [
    {
      name: 'popperRef',
      description: { cn: 'el-popper 组件实例', en: 'el-popper component instance' },
      type: 'object',
      param: 'Ref<PopperInstance | null>',
    },
    {
      name: 'contentRef',
      description: { cn: 'el-tooltip0-content 组件实例', en: 'el-tooltip-content component instance' },
      type: 'object',
      param: 'Ref<TooltipContentInstance | null>',
    },
    {
      name: 'isFocusInsideContent',
      description: {
        cn: '验证当前焦点事件是否在 el-tooltip-content 中触发',
        en: 'validate current focus event is trigger inside el-tooltip-content',
      },
      type: 'function',
      param: '() => boolean | undefined',
    },
    {
      name: 'updatePopper',
      description: { cn: '更新 el-popper组件实例', en: 'update el-popper component instance' },
      type: 'function',
      param: '() => void',
    },
    {
      name: 'onOpen',
      description: { cn: '用于手动显示tooltip', en: 'expose onOpen function to mange el-tooltip open state' },
      type: 'function',
      param: '(event?: Event | undefined) => void',
    },
    {
      name: 'onClose',
      description: { cn: '用于手动关闭tooltip', en: 'expose onClose function to mange el-tooltip open state' },
      type: 'function',
      param: '',
    },
    {
      name: 'hide',
      description: { cn: '提供 hide 方法', en: 'expose hide function' },
      type: 'function',
      param: '(event?: Event | undefined) => void',
    },
  ],
  slots: [
    {
      name: 'default',
      description: { cn: 'Tooltip 触发引用的元素', en: 'Tooltip triggering &amp; reference element' },
    },
    {
      name: 'content',
      description: { cn: '自定义内容', en: 'customize content' },
    },
  ],
};
export default doc;
